#!/usr/bin/env python3
"""Generate the simplified collision-only CampusCollision model.

The visual Campus model applies a z offset of -0.25 m to Campus_world.obj.
This generator keeps that same alignment for material-filtered collision
meshes and uses explicit primitive boxes for the Go2 spawn / Nav2 test zone.
"""

from __future__ import annotations

import math
from collections import defaultdict
from pathlib import Path


MODEL_NAME = "CampusCollision"
VISUAL_Z_OFFSET = -0.25

CORE_CENTER_X = 41.45
CORE_CENTER_Y = -126.66
CORE_YAW = -0.516
CORE_HALF_LENGTH = 44.0
CORE_HALF_WIDTH = 8.0
CORE_SURFACE_TOP_Z = -0.05

GROUND_MATERIAL_GROUPS = {
    "road_surface": ("Road",),
    "pavement_surface": ("Pavement",),
    "road_rim_boundary": ("RoadRim",),
    "grass_surface": ("Grass",),
    "wall_boundary": ("Wall", "Wall_Grey"),
}

CORE_REPLACED_MATERIALS = {"Road", "Pavement", "RoadRim"}
GROUND_MATERIALS = set().union(*GROUND_MATERIAL_GROUPS.values())
GROUND_MATERIALS.update(
    {
        "Floor_Beige",
        "Floor_Browntiles",
        "Floor_GreyCarpet",
        "Floor_LightCarpet",
    }
)


def local_core_xy(x: float, y: float) -> tuple[float, float]:
    dx = x - CORE_CENTER_X
    dy = y - CORE_CENTER_Y
    c = math.cos(CORE_YAW)
    s = math.sin(CORE_YAW)
    return c * dx + s * dy, -s * dx + c * dy


def face_centroid(face: list[int], vertices: list[tuple[float, float, float] | None]):
    count = len(face)
    sx = sy = sz = 0.0
    for vertex_id in face:
        vertex = vertices[vertex_id]
        assert vertex is not None
        sx += vertex[0]
        sy += vertex[1]
        sz += vertex[2]
    return sx / count, sy / count, sz / count


def in_core_replacement_zone(x: float, y: float, margin: float = 0.0) -> bool:
    lx, ly = local_core_xy(x, y)
    return abs(lx) <= CORE_HALF_LENGTH + margin and abs(ly) <= CORE_HALF_WIDTH + margin


def parse_obj(path: Path):
    vertices: list[tuple[float, float, float] | None] = [None]
    faces_by_material: dict[str, list[list[int]]] = defaultdict(list)
    current_material: str | None = None

    with path.open("r", encoding="utf-8", errors="ignore") as stream:
        for line in stream:
            if line.startswith("v "):
                _, x, y, z, *_ = line.split()
                vertices.append((float(x), float(y), float(z)))
            elif line.startswith("usemtl "):
                current_material = line.split(None, 1)[1].strip()
            elif line.startswith("f ") and current_material:
                face = []
                for token in line.split()[1:]:
                    vertex_id = int(token.split("/")[0])
                    if vertex_id < 0:
                        vertex_id = len(vertices) + vertex_id
                    face.append(vertex_id)
                faces_by_material[current_material].append(face)

    return vertices, faces_by_material


def write_filtered_obj(
    output_path: Path,
    material_names: tuple[str, ...],
    vertices: list[tuple[float, float, float] | None],
    faces_by_material: dict[str, list[list[int]]],
) -> int:
    selected_faces: list[list[int]] = []

    for material in material_names:
        for face in faces_by_material.get(material, []):
            cx, cy, _ = face_centroid(face, vertices)
            if material in CORE_REPLACED_MATERIALS and in_core_replacement_zone(cx, cy):
                continue
            selected_faces.append(face)

    triangles: list[tuple[int, int, int]] = []
    for face in selected_faces:
        if len(face) < 3:
            continue
        for index in range(1, len(face) - 1):
            triangles.append((face[0], face[index], face[index + 1]))

    used_vertices = sorted({vertex_id for triangle in triangles for vertex_id in triangle})
    remap = {old_id: new_id for new_id, old_id in enumerate(used_vertices, start=1)}
    normal_accumulator = {old_id: [0.0, 0.0, 0.0] for old_id in used_vertices}

    for triangle in triangles:
        a = vertices[triangle[0]]
        b = vertices[triangle[1]]
        c = vertices[triangle[2]]
        assert a is not None and b is not None and c is not None
        ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
        vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
        nx = uy * vz - uz * vy
        ny = uz * vx - ux * vz
        nz = ux * vy - uy * vx
        length = math.sqrt(nx * nx + ny * ny + nz * nz)
        if length <= 1e-12:
            nx, ny, nz = 0.0, 0.0, 1.0
        else:
            nx, ny, nz = nx / length, ny / length, nz / length
        for old_id in triangle:
            normal_accumulator[old_id][0] += nx
            normal_accumulator[old_id][1] += ny
            normal_accumulator[old_id][2] += nz

    with output_path.open("w", encoding="utf-8") as stream:
        stream.write(f"# Generated by scripts/generate_campus_collision.py\n")
        stream.write(f"# Source materials: {', '.join(material_names)}\n")
        stream.write(f"o {output_path.stem}\n")
        for old_id in used_vertices:
            vertex = vertices[old_id]
            assert vertex is not None
            stream.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
        for old_id in used_vertices:
            nx, ny, nz = normal_accumulator[old_id]
            length = math.sqrt(nx * nx + ny * ny + nz * nz)
            if length <= 1e-12:
                nx, ny, nz = 0.0, 0.0, 1.0
            else:
                nx, ny, nz = nx / length, ny / length, nz / length
            stream.write(f"vn {nx:.6f} {ny:.6f} {nz:.6f}\n")
        for triangle in triangles:
            mapped = " ".join(
                f"{remap[vertex_id]}//{remap[vertex_id]}" for vertex_id in triangle
            )
            stream.write(f"f {mapped}\n")

    return len(triangles)


def connected_components(faces: list[list[int]]):
    vertex_to_faces: dict[int, list[int]] = defaultdict(list)
    for face_index, face in enumerate(faces):
        for vertex_id in face:
            vertex_to_faces[vertex_id].append(face_index)

    seen = [False] * len(faces)
    for start_index in range(len(faces)):
        if seen[start_index]:
            continue
        stack = [start_index]
        seen[start_index] = True
        component_faces = []
        component_vertices = set()
        while stack:
            face_index = stack.pop()
            component_faces.append(face_index)
            for vertex_id in faces[face_index]:
                component_vertices.add(vertex_id)
                for neighbor in vertex_to_faces[vertex_id]:
                    if not seen[neighbor]:
                        seen[neighbor] = True
                        stack.append(neighbor)
        yield component_faces, component_vertices


def make_obstacle_primitives(
    vertices: list[tuple[float, float, float] | None],
    faces_by_material: dict[str, list[list[int]]],
):
    obstacles = []
    cylinder_keywords = ("Plant", "Shrub", "Visitor", "Lamp", "LP")

    for material, faces in faces_by_material.items():
        if material in GROUND_MATERIALS:
            continue
        for component_faces, component_vertices in connected_components(faces):
            xs = []
            ys = []
            zs = []
            for vertex_id in component_vertices:
                vertex = vertices[vertex_id]
                assert vertex is not None
                xs.append(vertex[0])
                ys.append(vertex[1])
                zs.append(vertex[2])

            min_x, max_x = min(xs), max(xs)
            min_y, max_y = min(ys), max(ys)
            min_z, max_z = min(zs), max(zs)
            size_x = max_x - min_x
            size_y = max_y - min_y
            size_z = max_z - min_z
            center_x = (min_x + max_x) * 0.5
            center_y = (min_y + max_y) * 0.5
            local_x, local_y = local_core_xy(center_x, center_y)

            if not in_core_replacement_zone(center_x, center_y, margin=1.0):
                continue
            if abs(local_x) < 5.0 and abs(local_y) < 3.2:
                continue
            if len(component_faces) < 20:
                continue
            if size_z < 0.25 or size_x * size_y < 0.04:
                continue

            obstacles.append(
                {
                    "material": material,
                    "faces": len(component_faces),
                    "shape": "cylinder"
                    if any(keyword in material for keyword in cylinder_keywords)
                    else "box",
                    "center": (
                        center_x,
                        center_y,
                        (min_z + max_z) * 0.5 + VISUAL_Z_OFFSET,
                    ),
                    "size": (max(size_x, 0.08), max(size_y, 0.08), max(size_z, 0.10)),
                }
            )

    obstacles.sort(key=lambda item: (-item["faces"], item["material"]))
    return obstacles[:32]


def surface_xml(mu: float = 1.2) -> str:
    return f"""\
          <surface>
            <friction>
              <ode>
                <mu>{mu:.1f}</mu>
                <mu2>{mu:.1f}</mu2>
              </ode>
            </friction>
            <bounce>
              <restitution_coefficient>0.0</restitution_coefficient>
              <threshold>100000.0</threshold>
            </bounce>
            <contact>
              <ode>
                <kp>1000000.0</kp>
                <kd>1.0</kd>
                <max_vel>0.1</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
          </surface>"""


def box_collision_xml(name: str, pose: tuple[float, float, float, float, float, float], size):
    x, y, z, roll, pitch, yaw = pose
    sx, sy, sz = size
    return f"""\
        <collision name="{name}">
          <pose>{x:.6f} {y:.6f} {z:.6f} {roll:.6f} {pitch:.6f} {yaw:.6f}</pose>
          <geometry>
            <box>
              <size>{sx:.6f} {sy:.6f} {sz:.6f}</size>
            </box>
          </geometry>
{surface_xml()}
        </collision>"""


def cylinder_collision_xml(
    name: str,
    pose: tuple[float, float, float, float, float, float],
    radius: float,
    length: float,
):
    x, y, z, roll, pitch, yaw = pose
    return f"""\
        <collision name="{name}">
          <pose>{x:.6f} {y:.6f} {z:.6f} {roll:.6f} {pitch:.6f} {yaw:.6f}</pose>
          <geometry>
            <cylinder>
              <radius>{radius:.6f}</radius>
              <length>{length:.6f}</length>
            </cylinder>
          </geometry>
{surface_xml()}
        </collision>"""


def mesh_collision_xml(name: str, mesh_name: str, mu: float = 1.1):
    return f"""\
        <collision name="{name}">
          <pose>0 0 {VISUAL_Z_OFFSET:.6f} 0 0 0</pose>
          <geometry>
            <mesh>
              <uri>model://{MODEL_NAME}/meshes/{mesh_name}</uri>
            </mesh>
          </geometry>
{surface_xml(mu)}
        </collision>"""


def local_box_pose(local_x: float, local_y: float, z: float):
    c = math.cos(CORE_YAW)
    s = math.sin(CORE_YAW)
    return (
        CORE_CENTER_X + c * local_x - s * local_y,
        CORE_CENTER_Y + s * local_x + c * local_y,
        z,
        0.0,
        0.0,
        CORE_YAW,
    )


def core_primitive_collisions():
    road_height = 0.08
    sidewalk_height = 0.08
    curb_height = 0.14
    road_center_z = CORE_SURFACE_TOP_Z - road_height * 0.5
    sidewalk_top_z = CORE_SURFACE_TOP_Z + 0.08
    sidewalk_center_z = sidewalk_top_z - sidewalk_height * 0.5
    curb_center_z = CORE_SURFACE_TOP_Z + 0.05 - curb_height * 0.5

    collisions = [
        box_collision_xml(
            "core_road_main_collision",
            local_box_pose(0.0, 0.0, road_center_z),
            (88.0, 5.4, road_height),
        ),
        box_collision_xml(
            "core_sidewalk_left_collision",
            local_box_pose(0.0, 4.25, sidewalk_center_z),
            (88.0, 2.4, sidewalk_height),
        ),
        box_collision_xml(
            "core_sidewalk_right_collision",
            local_box_pose(0.0, -4.25, sidewalk_center_z),
            (88.0, 2.4, sidewalk_height),
        ),
    ]

    # Split curbs around a 4 m curb-cut at the spawn point. This keeps the
    # local planner honest about road edges without trapping the initial pose.
    for side_name, side_y in (("left", 2.85), ("right", -2.85)):
        for segment_name, segment_x in (("front", 24.0), ("rear", -24.0)):
            collisions.append(
                box_collision_xml(
                    f"core_curb_{side_name}_{segment_name}_collision",
                    local_box_pose(segment_x, side_y, curb_center_z),
                    (40.0, 0.16, curb_height),
                )
            )

    # Low ramp plates fill the curb-cut gap so Go2 and Nav2 can test transitions
    # between the road and sidewalk without an invisible discontinuity.
    for side_name, side_y in (("left", 3.35), ("right", -3.35)):
        collisions.append(
            box_collision_xml(
                f"core_curb_cut_{side_name}_ramp_collision",
                local_box_pose(0.0, side_y, CORE_SURFACE_TOP_Z + 0.01),
                (4.0, 1.0, 0.04),
            )
        )

    return collisions


def generate_model_sdf(mesh_counts: dict[str, int], obstacles):
    collisions = []
    collisions.extend(core_primitive_collisions())
    collisions.extend(
        [
            mesh_collision_xml("road_surface_collision", "road_surface_collision.obj", 1.1),
            mesh_collision_xml(
                "pavement_surface_collision", "pavement_surface_collision.obj", 1.2
            ),
            mesh_collision_xml(
                "road_rim_boundary_collision", "road_rim_boundary_collision.obj", 1.0
            ),
            mesh_collision_xml("grass_surface_collision", "grass_surface_collision.obj", 0.9),
            mesh_collision_xml("wall_boundary_collision", "wall_boundary_collision.obj", 1.0),
        ]
    )

    for index, obstacle in enumerate(obstacles, start=1):
        x, y, z = obstacle["center"]
        sx, sy, sz = obstacle["size"]
        name = f"core_obstacle_{index:02d}_{obstacle['material'].lower().replace('.', '_')}_collision"
        if obstacle["shape"] == "cylinder":
            radius = min(max(sx, sy) * 0.5, 3.0)
            collisions.append(cylinder_collision_xml(name, (x, y, z, 0.0, 0.0, 0.0), radius, sz))
        else:
            collisions.append(box_collision_xml(name, (x, y, z, 0.0, 0.0, 0.0), (sx, sy, sz)))

    mesh_summary = ", ".join(f"{name}={count}" for name, count in sorted(mesh_counts.items()))
    return f"""<?xml version="1.0" ?>
<sdf version="1.9">
  <model name="{MODEL_NAME}">
    <static>true</static>
    <!--
      Collision-only companion for model://Campus.
      Generated material mesh face counts: {mesh_summary}.
      The high-resolution Campus_world.obj remains visual-only in model://Campus.
    -->
    <link name="collision_link">
{chr(10).join(collisions)}
    </link>
  </model>
</sdf>
"""


def main():
    model_dir = Path(__file__).resolve().parents[1]
    models_dir = model_dir.parent
    source_obj = models_dir / "Campus" / "meshes" / "Campus_world.obj"
    meshes_dir = model_dir / "meshes"
    meshes_dir.mkdir(parents=True, exist_ok=True)

    vertices, faces_by_material = parse_obj(source_obj)

    mesh_counts = {}
    for group_name, materials in GROUND_MATERIAL_GROUPS.items():
        mesh_counts[group_name] = write_filtered_obj(
            meshes_dir / f"{group_name}_collision.obj",
            materials,
            vertices,
            faces_by_material,
        )

    obstacles = make_obstacle_primitives(vertices, faces_by_material)
    (model_dir / "model.sdf").write_text(
        generate_model_sdf(mesh_counts, obstacles),
        encoding="utf-8",
    )

    print(f"Generated {MODEL_NAME} with {len(obstacles)} simplified core obstacles.")
    for group_name, count in sorted(mesh_counts.items()):
        print(f"  {group_name}: {count} faces")


if __name__ == "__main__":
    main()
